import type { Place } from "./types";
import { VALENCIA_CENTER, haversineMeters } from "./geo";

export const TAGS = [
  "Можно с ноутбуком",
  "Веранда",
  "Завтраки",
  "Десерты",
] as const;

// Seed data from mesta_coffee_valencia.xlsx — real coffee shops, coordinates verified via
// Google Maps. status "draft": owner language not yet confirmed in person (see plan §11.2).
const RAW: Omit<Place, "distanceM">[] = [
  {
    id: "the-miners-coffee-franca",
    slug: "the-miners-coffee-franca",
    name: "The Miners Coffee Franca",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "Camins al Grau",
    address: "Av. de França, 36",
    lat: 39.4588908,
    lng: -0.3469398,
    tags: ["pet-friendly", "matcha", "можно с ноутбуком"],
    description:
      "Проверить: русскоязычные владельцы/персонал? В отзывах явных признаков нет — уточнить лично.",
    hours: "Пн–Вс 8:00–19:00",
    openUntil: "19:00",
    isOpenNow: true,
    googleMapsUrl: "https://maps.app.goo.gl/c5gNzXG2vuVWrrU37",
  },
  {
    id: "cultura-coffee-republic",
    slug: "cultura-coffee-republic",
    name: "Cultura Coffee Republic",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "Algirós",
    address: "Carrer de Ramon Llull, 6",
    lat: 39.4750569,
    lng: -0.347065,
    tags: ["можно с ноутбуком", "рядом с универом", "завтраки"],
    description:
      "Проверить: русскоязычные владельцы/персонал? В отзывах не упоминается напрямую.",
    hours: "Пн–Вс 8:00–20:00",
    openUntil: "20:00",
    isOpenNow: true,
    phone: "+34 604 85 89 35",
    googleMapsUrl: "https://maps.app.goo.gl/ddkYE67xm39y5H7r7",
  },
  {
    id: "brio-specialty-coffee-brunch",
    slug: "brio-specialty-coffee-brunch",
    name: "Brio. Specialty Coffee & Brunch",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "Quatre Carreres",
    address: "Carrer de Luis Arcas, 9",
    lat: 39.4557473,
    lng: -0.3588776,
    tags: ["брунч", "веранда"],
    description:
      "В отзыве упомянут «Ukrainian quality» сервиса — похоже на украинских/русскоязычных владельцев, но нужно подтвердить лично. Недавно открылись.",
    hours: "Пн–Вс 9:00–17:00",
    openUntil: "17:00",
    isOpenNow: true,
    googleMapsUrl: "https://maps.app.goo.gl/eoKpfdYqyaFgmiZa9",
  },
  {
    id: "velvet-cafe",
    slug: "velvet-cafe",
    name: "Velvet Café",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "L'Eixample",
    address: "Gran Via del Marqués del Túria, 21",
    lat: 39.4659739,
    lng: -0.3722056,
    tags: ["брунч", "десерты"],
    description:
      "Отзыв прямо говорит «run by Ukrainians» — сильный кандидат, но подтвердить при личном визите. В меню сырники.",
    hours: "Пн–Пт 9:00–20:00, Сб–Вс 10:00–20:00",
    openUntil: "20:00",
    isOpenNow: true,
    phone: "+34 611 52 86 25",
    googleMapsUrl: "https://maps.app.goo.gl/RmFZhCXASrbWAzyG6",
  },
  {
    id: "pom-pom",
    slug: "pom-pom",
    name: "Pom Pom",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "Ciutat Vella",
    address: "Av. de l'Oest, 28",
    lat: 39.4718785,
    lng: -0.3799081,
    tags: ["десерты", "можно с ноутбуком", "pet-friendly"],
    description:
      "В отзывах упомянуты сырники и холодник — вероятно русскоязычная кухня/владельцы, подтвердить лично.",
    hours: "Пн–Пт 9:00–19:00, Сб 10:00–20:00, Вс 10:00–19:00",
    openUntil: "19:00",
    isOpenNow: true,
    phone: "+34 614 15 88 07",
    googleMapsUrl: "https://maps.app.goo.gl/r86faSQ6ndSyXar27",
  },
  {
    id: "in-coffee-tea",
    slug: "in-coffee-tea",
    name: "I`N Coffee&Tea — Café de especialidad",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "Ciutat Vella",
    address: "C/ del Dr. Romagosa, 5",
    lat: 39.470681,
    lng: -0.3723597,
    tags: ["можно с ноутбуком", "чай"],
    description:
      "В отзыве прямо: «Staff speaks Russian, English and Spanish», в меню медовик и наполеон — хороший кандидат.",
    hours: "Пн–Пт 9:00–20:00, Сб–Вс 10:00–20:00",
    openUntil: "20:00",
    isOpenNow: true,
    phone: "+34 673 27 82 09",
    googleMapsUrl: "https://maps.app.goo.gl/uvTdU3UA6ohTfhDD7",
  },
  {
    id: "fiveo-coffee",
    slug: "fiveo-coffee",
    name: "Fiveo Coffee",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "L'Eixample",
    address: "C/ del Doctor Serrano, 1",
    lat: 39.4624108,
    lng: -0.3721554,
    tags: ["дизайнерский интерьер", "кофе навынос"],
    description:
      "Проверить: русскоязычные владельцы/персонал? В отзывах не упоминается напрямую.",
    hours: "Пн–Чт 8:00–19:00, Пт 8:30–19:30, Сб 9:00–19:30, Вс 9:00–19:00",
    openUntil: "19:00",
    isOpenNow: true,
    googleMapsUrl: "https://maps.app.goo.gl/823fRzCHavrejwRe8",
  },
  {
    id: "fav-coffee-cronista",
    slug: "fav-coffee-cronista",
    name: "FAV Coffee",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "Ciutat Vella",
    address: "C/ del Cronista Carreres, 1",
    lat: 39.4730033,
    lng: -0.368647,
    tags: ["выпечка (бабка)", "можно с ноутбуком"],
    description:
      "Проверить: русскоязычные владельцы/персонал? Возможно сеть — см. вторую точку (Camins al Grau).",
    hours: "Пн–Пт 8:00–20:00, Сб–Вс 9:00–18:00",
    openUntil: "20:00",
    isOpenNow: true,
    googleMapsUrl: "https://maps.app.goo.gl/ZbisoHZqmYWiAQC96",
  },
  {
    id: "fav-coffee-mancebo",
    slug: "fav-coffee-mancebo",
    name: "FAV Coffee — Specialty Coffee and Brunch",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "Camins al Grau",
    address: "C/ d'Andrés Mancebo, 40",
    lat: 39.4643151,
    lng: -0.3559679,
    tags: ["брунч", "выпечка"],
    description:
      "Похоже, вторая точка сети FAV Coffee — проверить, не дубль ли одного бренда, объединять ли в один тег/владельца.",
    hours: "Пн–Пт 8:00–20:00, Сб–Вс 9:00–18:00",
    openUntil: "20:00",
    isOpenNow: true,
    googleMapsUrl: "https://maps.app.goo.gl/XAhKBdfc7G5xcHe76",
  },
  {
    id: "pals-cafe",
    slug: "pals-cafe",
    name: "Pals Cafe. Specialty Coffee and Breakfast",
    category: "coffee",
    categoryLabel: "Кофейня",
    district: "Extramurs",
    address: "Carrer Mestre Palau, 4",
    lat: 39.4716202,
    lng: -0.3843595,
    tags: ["завтраки", "веганские опции"],
    description:
      "Проверить: русскоязычные владельцы/персонал? В отзывах не упоминается напрямую.",
    hours: "Пн–Пт 8:30–16:30, Сб–Вс 9:00–17:00",
    openUntil: "16:30",
    isOpenNow: true,
    googleMapsUrl: "https://maps.app.goo.gl/vxd7bXcuDGizKVTX7",
  },
];

export const PLACES: Place[] = RAW.map((p) => ({
  ...p,
  distanceM: Math.round(haversineMeters(VALENCIA_CENTER.lat, VALENCIA_CENTER.lng, p.lat, p.lng)),
}));
